### PR TITLE
VIH-10635 check if details match deleted users when checking for next available username

### PR DESCRIPTION
**Pull request by shaed-parkar**
### Jira link (if applicable)

VIH-10635

### Change description ###

check deleted resources for match by given and surname to find next available username

### CODE REVIEW

**Review by will-craig — DISMISSED** [review]

**Review by marcogagliardi — DISMISSED** [review]
lg2m

**Review by will-craig — APPROVED** [review]

**Review by komaldabhi1509 — APPROVED** [review]

**Pull request merged**
